// VBConversions Note: VB project level imports
using System.Collections.Generic;
using System;
using System.Diagnostics;
using System.Data;
using Microsoft.VisualBasic;
using System.Collections;
// End of VB project level imports

using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.ComponentModel;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdressenManagement.Module
{
    namespace MainModel
    {

        public partial class FehlerProtokoll : XPObject
        {
            DateTime fZeitstempel;
            public DateTime Zeitstempel
            {
                get
                {
                    return fZeitstempel;
                }
                set
                {
                    SetPropertyValue<DateTime>("Zeitstempel", ref fZeitstempel, value);
                }
            }
            string fAngemeldeterBenutzer;
            public string AngemeldeterBenutzer
            {
                get
                {
                    return fAngemeldeterBenutzer;
                }
                set
                {
                    SetPropertyValue<string>("AngemeldeterBenutzer", ref fAngemeldeterBenutzer, value);
                }
            }
            string fGewaehltesObjekt;
            [Size(150)]
            public string GewaehltesObjekt
            {
                get
                {
                    return fGewaehltesObjekt;
                }
                set
                {
                    SetPropertyValue<string>("GewaehltesObjekt", ref fGewaehltesObjekt, value);
                }
            }
            string fAktion;
            [Size(150)]
            public string Aktion
            {
                get
                {
                    return fAktion;
                }
                set
                {
                    SetPropertyValue<string>("Aktion", ref fAktion, value);
                }
            }
            string fFehlermeldung;
            [Size(SizeAttribute.Unlimited)]
            public string Fehlermeldung
            {
                get
                {
                    return fFehlermeldung;
                }
                set
                {
                    SetPropertyValue<string>("Fehlermeldung", ref fFehlermeldung, value);
                }
            }
        }

    }

}
