// VBConversions Note: VB project level imports
using System.Collections.Generic;
using System;
using System.Diagnostics;
using System.Data;
using Microsoft.VisualBasic;
using System.Collections;
// End of VB project level imports

using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.ComponentModel;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdressenManagement.Module
{
	namespace MainModel
	{
		
		public partial class ProduktBericht : XPObject
		{
			int fProduktID;
public int ProduktID
			{
				get
				{
					return fProduktID;
				}
				set
				{
                    SetPropertyValue<int>("ProduktID", ref fProduktID, value);
				}
			}
			string fProduktTyp;
public string ProduktTyp
			{
				get
				{
					return fProduktTyp;
				}
				set
				{
                    SetPropertyValue<string>("ProduktTyp", ref fProduktTyp, value);
				}
			}
			int fProduktTypID;
public int ProduktTypID
			{
				get
				{
					return fProduktTypID;
				}
				set
				{
                    SetPropertyValue<int>("ProduktTypID", ref fProduktTypID, value);
				}
			}
			string fProdukt;
public string Produkt
			{
				get
				{
					return fProdukt;
				}
				set
				{
                    SetPropertyValue<string>("Produkt", ref fProdukt, value);
				}
			}
			bool fVorgefuehrt;
public bool Vorgefuehrt
			{
				get
				{
					return fVorgefuehrt;
				}
				set
				{
                    SetPropertyValue<bool>("Vorgefuehrt", ref fVorgefuehrt, value);
				}
			}
			bool fVerkauft;
public bool Verkauft
			{
				get
				{
					return fVerkauft;
				}
				set
				{
					SetPropertyValue<bool>("Verkauft", ref fVerkauft, value);
				}
			}
			bool fVerschenkt;
public bool Verschenkt
			{
				get
				{
					return fVerschenkt;
				}
				set
				{
					SetPropertyValue<bool>("Verschenkt", ref fVerschenkt, value);
				}
			}
			decimal fProduktPreis;
public decimal ProduktPreis
			{
				get
				{
					return fProduktPreis;
				}
				set
				{
					SetPropertyValue<decimal>("ProduktPreis", ref fProduktPreis, value);
				}
			}
		}
		
	}
	
}
